---
title: "Probability: Chapter 1 - Combinatorial Analysis"
author: "Joshua Ingram"
output: pdf_document
fontsize: 11pt
geometry: margin=0.5in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.2 The Basic Principles of Counting

If *r* experiments are to be performed where experiment 1 has $n_1$ possible outcomes, and for each outcome of experiment 1 there are $n_2$ possible outcomes of experiment 2, etc...

Then there is a total of 

$$
\boxed{\mathbf{n_1 \cdot n_2 \cdot ... \cdot n_r}}
$$ 

possible outcomes from the r experiments

# 1.3 Permutations

***Permutation*** - an arrangement of objects where order matters *(e.g. abc is distinct from acb)*

### Calculate Number of Permutations

For n objects, there are

$$
\boxed{n\cdot(n-1)\cdot(n-2)\cdot...\cdot3\cdot2\cdot1 = n!}
$$
permutations

- There is *no replacement*

### Permutations with Identical Objects

For n objects where $n_1$ are alike, $n_2$ are alike, ... , $n_r$ are alike, there are

$$
\boxed{\frac{n!}{n_1!n_2!...n_r!}}
$$

different permutations

# 1.4 Combinations

***Combination*** - arrangement of objects where order does not matter *(e.g. abc = bca, abc $\neq$ abd)*

### Combinations of size r from n Objects

For n objects, there are

$$
\boxed{\binom{n}{r} = \frac{n!}{(n-r)!r!}}
$$

combinations of size r

### Pascal's Identity

$$
\boxed{\binom{n}{r} = \binom{n-1}{r-1} + \binom{n-1}{r}} \; \; 1 \le r \le n
$$

### The Binomial Theorem

$$
\boxed{(x+y)^k = \sum^n_{k=0}\binom{n}{k}x^{k}y^{n-k}}
$$

# 1.5 Multinomial Coefficients

### Finding all Possible Divisons of Groups

For $n$ distinct items that are to be divided into $r$ groups of size $n_1,...,n_r$, such that $\sum_{i=1}^rn_i = n$, there are

$$
\boxed{\binom{n}{n_1,n_2,...,n_r} = \frac{n!}{n_1!n_2!...n_r!}}
$$

different divisions


### The Multinomial Theorem

$$
\boxed{(x_1 + x_2 + ... + x_r)^k = \sum_{n_1,...n_r:n_1+...n_r=n}\binom{n}{n_1,n_2,...n_r}x_1^{n_1}x_2^{n_2}...x_r^{n_r}}
$$

# 1.6 The Number of Integer Solutions of Equations

### Positive Integer Solutions

There are

$$
\boxed{\binom{n-1}{r-1}}
$$

distinct positive-valued vectors satisfying: $x_1+x_2+...+x_r=n$

### Nonnegative Integer Solutions

There are

$$
\boxed{\binom{n+r-1}{r-1}}
$$

distinct nonnegative integer-valued vectors satisfying: $x_1+x_2+...+x_r=n$